/**
 * Short, premium pre-game countdown lines. Rotate during the 30s wait so the countdown feels alive.
 * Used in the main overlay; keep copy tasteful and product-quality. Multiple lines rotate so it never feels static.
 */
export const PREGAME_COUNTDOWN_LINES: readonly string[] = [
  "Match locked in.",
  "Arena syncing.",
  "Players ready.",
  "Bets closing.",
  "Board loading.",
  "Get set.",
  "Almost there.",
  "Stay with us.",
  "Here we go.",
  "Game begins in…",
  "Stand by for first move.",
  "Final call.",
  "Lock in.",
  "Ready when you are.",
]

/**
 * ~300 rotating pre-game countdown phrases. Playful, hype, competitive, witty.
 * Used during the 30-second wait so the countdown feels alive and entertaining.
 */
export const COUNTDOWN_PHRASES: readonly string[] = [
  "Stretch those fingers.",
  "No excuses after this.",
  "Your opponent is pretending not to sweat.",
  "Thirty seconds to greatness.",
  "Chat is already judging.",
  "This is where legends misclick.",
  "Victory is loading.",
  "Last chance to act calm.",
  "The crowd is pretending they knew the winner all along.",
  "Somebody just bet like they saw the future.",
  "Smart money and dumb luck are both in the room.",
  "Last call before chaos begins.",
  "Knights are stretching before battle.",
  "Crowd money is starting to heat up.",
  "Last-minute action hitting the market.",
  "Smart money is circling the underdog.",
  "Bets are flying before lock.",
  "Crowns up. Match ignition incoming.",
  "The house always wins. Just kidding. Maybe.",
  "Place your bets. No refunds after zero.",
  "T-minus something. Get ready.",
  "Dark horse energy in the room.",
  "Diamond hands only past this point.",
  "To the moon or to the lobby. Your call.",
  "Pre-match circus. You're in it.",
  "Best seat in the house. Don't leave.",
  "Cards on the table in 30 seconds.",
  "Someone's about to win. Might be you.",
  "Final call. Actually we have a timer.",
  "Spice level: about to go live.",
  "Only the bold stay past zero.",
  "Swords up. Match is loading.",
  "Odds are odds. Bet with your head.",
  "Eagle eye on the board. Get set.",
  "Dragon energy. Match incoming.",
  "Shields up. Countdown active.",
  "Fanfare in 3… 2… 1…",
  "Magnetic pull to the arena.",
  "Fortune favors the ready.",
  "Crystal ball says: place your side.",
  "Coins in. No take-backs at zero.",
  "Drama in 30. Stay tuned.",
  "Smart foxes lock in now.",
  "Wolves are circling. Join or watch.",
  "Last sips before the board drops.",
  "Rock solid? Lock your side.",
  "Joker's wild. Timer's not.",
  "Step right up. Timer's running.",
  "Bell's about to ring. Get set.",
  "Hype train. All aboard.",
  "Last chance aisle. Betting closes at zero.",
  "Pieces moving soon. Stay put.",
  "Masterpiece in progress. You're in it.",
  "Medals not handed out yet. Compete.",
  "Wave of action incoming.",
  "Butterfly effect. Your bet matters.",
  "Lab conditions. Fair play only.",
  "Bullseye in 30. Aim now.",
  "Fuse lit. Stand clear at zero.",
  "Director says action in 30.",
  "Wise owls have already locked in.",
  "Luck is a factor. So is the timer.",
  "Key moment. Don't close the tab.",
  "Light as a feather. Stakes are not.",
  "Steady hands win. Timer's ticking.",
  "Hot take: lock your side now.",
  "Fingers warmed up? Good.",
  "Opponent is double-checking the rules.",
  "The arena is watching.",
  "No backsies once the clock hits zero.",
  "Glory or lobby. Pick one.",
  "Your future self will thank or blame you.",
  "Spectators are taking notes.",
  "One of you is about to look very smart.",
  "The board doesn't care about your feelings.",
  "Thirty seconds of hope left.",
  "Make it count.",
  "Nerves are a feature, not a bug.",
  "Last chance to breathe.",
  "The timer is not your friend. Or is it.",
  "Victory tastes better when you waited for it.",
  "Your click finger is ready. We hope.",
  "Both players are definitely not panicking.",
  "The crowd has already chosen a favorite. Probably.",
  "History is written in the next 30 seconds.",
  "No pressure. Okay, some pressure.",
  "The calm before the misclick.",
  "Your strategy is perfect. Probably.",
  "Thirty seconds until someone's day gets better.",
  "And someone's gets worse.",
  "The arena announcer is losing his voice already.",
  "Trash talk optional. Focus mandatory.",
  "Stakes: high. Timer: ticking.",
  "May the best board state win.",
  "Your opponent is also reading this.",
  "Synchronize your confidence.",
  "The server is judging both of you equally.",
  "No take-backs. The timer said so.",
  "Legends are made in the next half-minute.",
  "Or memes. One of those.",
  "The board awaits. So does the clock.",
  "Channel your inner champion. Or chaos.",
  "Thirty seconds to prove something. Or nothing.",
  "The crowd has popcorn. You have stakes.",
  "Your mouse or touchscreen is ready. We hope.",
  "No refunds on regret.",
  "The timer believes in you. Maybe.",
  "One of you is about to be very happy.",
  "The other one will get 'em next time.",
  "Spectator bets are locking. So is the match.",
  "Glory, glory, thirty seconds.",
  "Your opponent is definitely not reading this.",
  "They're totally reading this.",
  "The arena is vibrating with anticipation.",
  "Or that's just your nerves.",
  "Last chance to stretch.",
  "Fate is loading. Please wait.",
  "The board is buffering. Your courage isn't.",
  "Thirty seconds of pure possibility.",
  "Then it's just pure board game.",
  "Winners and losers: TBD in 30.",
  "The clock is the only impartial judge.",
  "Your strategy: intact. For 30 more seconds.",
  "Then we'll see.",
  "No do-overs. Timer's rules.",
  "The arena respects the countdown.",
  "So should you.",
  "Thirty. Seconds.",
  "Make them count. Or don't. Your call.",
  "The crowd is ready. Are you?",
  "Opponent status: also waiting.",
  "Mutual anxiety: activated.",
  "The board is loading. So is destiny.",
  "Or something less dramatic. But still.",
  "Fingers on the trigger. Metaphorically.",
  "The timer has no mercy.",
  "Neither does the board. Usually.",
  "Thirty seconds to greatness or oops.",
  "We believe in you. The timer is neutral.",
  "Last chance to mentally rehearse.",
  "Or panic. Whatever works.",
  "The arena is ready. You're ready. Probably.",
  "Spectators are placing final bets.",
  "So is fate. Probably.",
  "No pressure. Just thirty seconds.",
  "Then infinite pressure. Fun.",
  "Your opponent is calm. Definitely calm.",
  "We're sure of it.",
  "The board is polished. So should your strategy be.",
  "Thirty seconds of hope and fear.",
  "Mostly hope. We hope.",
  "The clock is ticking. So is someone's heart.",
  "Maybe yours. Maybe theirs.",
  "Arena energy: maximum.",
  "Your energy: also hopefully maximum.",
  "Thirty seconds until someone wins.",
  "Or draws. We don't judge.",
  "The crowd is hyped. You're hyped. Match: loading.",
  "No backsies. No take-backs. No mercy.",
  "Just board game.",
  "Thirty seconds to become a legend.",
  "Or a cautionary tale. No in-between.",
  "We're kidding. There's totally in-between.",
  "The timer doesn't care about our jokes.",
  "Lock in. Or don't. Timer's still going.",
  "Your move. In thirty seconds.",
  "Not yet. Wait for it.",
  "The arena is patient. You should be too.",
  "For thirty more seconds.",
  "Then all bets are off. Literally.",
  "The board is ready. The clock is ready.",
  "Are you?",
  "Thirty seconds of pure anticipation.",
  "Then pure gameplay. We promise.",
  "Spectators are placing their final judgments.",
  "So is the timer. Constantly.",
  "No extensions. No mulligans. Timer said so.",
  "Your legacy starts in thirty seconds.",
  "Or your humility. One of those.",
  "The arena doesn't forget.",
  "Neither does the board.",
  "Thirty seconds. You've got this.",
  "Probably.",
  "Opponent is sweating. We assume.",
  "We're all sweating. It's fine.",
  "The clock is fair. So is the board.",
  "So is the outcome. Usually.",
  "Last chance to doubt yourself.",
  "Or to believe. Your call.",
  "Thirty seconds until the real fun starts.",
  "This is also fun. The waiting. Sure.",
  "The crowd thinks so. Maybe.",
  "Your fingers are ready. The board is ready.",
  "The timer is ready. You're ready. Go.",
  "In thirty seconds.",
  "Not yet.",
  "Patience. For thirty more seconds.",
  "Then unleash.",
  "The arena awaits. The board awaits.",
  "The timer awaits. Nobody awaits forever.",
  "Thirty seconds. Tops.",
  "Then it's go time.",
  "For real this time.",
  "We mean it.",
  "Probably.",
  "The board is loading. Your nerves are loading.",
  "Everything's loading. In thirty seconds: play.",
  "No more countdown messages after this one.",
  "Just kidding. There are more.",
  "The timer is relentless.",
  "So is the arena. So are we.",
  "Thirty seconds of hype.",
  "Then thirty minutes of gameplay. Or less. Who knows.",
  "The point is: get ready.",
  "Your opponent is getting ready.",
  "The board is getting ready.",
  "The whole arena is getting ready.",
  "In thirty seconds we're all ready. Go.",
  "Almost.",
  "Thirty. More. Seconds.",
  "We can do this.",
  "You can do this.",
  "They can do this.",
  "Everybody can do this. Probably.",
  "The timer believes in equality.",
  "Thirty seconds for everyone.",
  "No more. No less.",
  "Then: may the best move win.",
  "The arena is silent. With anticipation.",
  "Or we muted the crowd. One of those.",
  "Thirty seconds of calm.",
  "Then chaos. Fun chaos.",
  "Board game chaos. The best kind.",
  "Your strategy: locked in. We hope.",
  "Your nerves: also locked in. Sorry.",
  "The timer has no chill.",
  "Thirty seconds until it's go time.",
  "For real for real.",
  "We're not kidding this time.",
  "Okay we might be. But the timer isn't.",
  "Thirty seconds. That's it. That's the message.",
  "Go.",
  "Wait no. Not yet.",
  "Thirty seconds.",
  "Then go.",
  "Promise.",
  "The board is ready when you are.",
  "In thirty seconds you'd better be ready.",
  "The timer doesn't wait.",
  "Neither does your opponent.",
  "Neither does glory.",
  "Thirty seconds to glory. Or something.",
  "The arena is ready. The crowd is ready.",
  "You're ready. They're ready.",
  "Everybody's ready. In thirty seconds we start.",
  "For real.",
  "Final countdown. Not the song. The actual countdown.",
  "Thirty seconds.",
  "Make it good.",
  "Or make it memorable. Either works.",
  "The board remembers everything.",
  "So does the timer. So does the arena.",
  "Thirty seconds of fame. Or shame. Or draw.",
  "We don't judge. Much.",
  "Your opponent is not reading this.",
  "They're totally reading this.",
  "Everybody's reading this. It's the only thing to do.",
  "For thirty more seconds.",
  "Then we play.",
  "Finally.",
  "The arena has been waiting. You've been waiting.",
  "Thirty seconds. Then no more waiting.",
  "Just playing.",
  "And winning. Or losing. Or drawing.",
  "One of those. We'll see.",
  "The timer will tell. In thirty seconds.",
  "And then every second after that.",
  "Until someone wins. Or draws. You know.",
  "Thirty seconds. You've waited this long.",
  "What's thirty more?",
  "Everything. Everything is thirty more.",
  "Then it's game time.",
  "For real game time.",
  "No more countdown. Just count.",
  "Down. To zero. Then play.",
  "We're excited. You're excited.",
  "The board is excited. Probably.",
  "Thirty seconds of excitement.",
  "Then thirty minutes of more excitement. Hopefully.",
  "The arena doesn't do boring.",
  "Neither do we. Neither should you.",
  "Thirty seconds. Let's go.",
  "Almost let's go.",
  "Thirty seconds and then let's go.",
  "For real.",
  "Final final countdown.",
  "We mean it this time.",
  "Thirty. Seconds.",
  "Go time imminent.",
  "Board time imminent.",
  "Glory time imminent. Or something.",
  "The timer has spoken.",
  "Thirty seconds remain.",
  "Use them wisely. Or don't. We're not your boss.",
  "The board is your boss. In thirty seconds.",
  "Until then: breathe. Or don't. Your call.",
  "The arena supports you. Or the other guy. We're neutral.",
  "Thirty seconds of neutrality.",
  "Then we pick a winner. Or a draw. The board decides.",
  "We're just the messenger.",
  "The timer is also just a messenger.",
  "A very strict messenger.",
  "Thirty seconds. Message delivered.",
  "Over and out. Until zero.",
  "Then we're back. With a match. A real one.",
  "We promise.",
  "Thirty seconds. That's all.",
  "That's everything.",
  "For now.",
]
